modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="extrarocks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Extra Rocks" #mandatory
##displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="extrarocks.png" #optional
credits="I hear the Minecraft Mod Development discord channel is the cat's bananas" #optional
authors="Commoble"
description='''
Adds sixteen more rock variants
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.extrarocks]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[21.8.36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.extrarocks]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.21.8,1.21.9)"
    ordering="NONE"
    side="BOTH"
